services:
  app:
    build: .
    env_file: .env
    secrets:
      - jwt_private
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
    restart: unless-stopped
  postgres:
    image: postgres:16
    container_name: auth_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: auth_redis
    ports:
      - "6379"
    restart: unless-stopped

  # Если понадобится локальный Kafka:
  # zookeeper:
  #   image: confluentinc/cp-zookeeper:latest
  #   container_name: auth_zookeeper
  #   environment:
  #     ZOOKEEPER_CLIENT_PORT: 2181
  #   ports:
  #     - "2181:2181"
  # kafka:
  #   image: confluentinc/cp-kafka:latest
  #   container_name: auth_kafka
  #   depends_on:
  #     - zookeeper
  #   environment:
  #     KAFKA_BROKER_ID: 1
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  #   ports:
  #     - "9092:9092"

volumes:
  pgdata:

secrets:
  jwt_private:
    file: ./secrets/jwt-private.pem